### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by Kryomancer** [GarrettGunnell/Shell-Texturing#1]
The use of the code currently in the repository by anyone else is legally problematic since it has not been assigned any license terms. [If no license is presented, the default copyright protection provided by law applies meaning the code is effectively *all rights reserved* and nobody is permitted to use or edit it in any way.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) From a legal standpoint, nobody is allowed to fork and edit the code to take part in the challenge of improving the code you presented on Youtube, which I assume is likely not something you intended to do.

Likewise, it is unclear whether people are allowed to use your code or its derivatives in their own projects: 

- Do you allow its use in for-profit projects? 
- Do you allow its use in closed source projects? 
- Do you wish to require people to credit you, is it optional, or even discouraged?

A person careful about copyright may be discouraged from closely following the tutorial provided by the code as it might land their own code in a legal gray area of being similar enough to constitute a derivative work. A license could serve to clear up all of the above questions.

**Comment by GarrettGunnell** [comment]
fixed
